-- TradeHub V3 admin database additions
-- Run this after the V2 schema in your Supabase SQL Editor.

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id),
  action text not null,
  target_user_id uuid references auth.users(id),
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_logs enable row level security;

drop policy if exists "Admins read logs" on public.admin_logs;

create policy "Admins read logs"
on public.admin_logs for select
to authenticated
using ((select public.is_admin()));

create index if not exists admin_logs_created_at_idx
on public.admin_logs(created_at desc);

create index if not exists admin_logs_target_idx
on public.admin_logs(target_user_id);

-- Privileged admin actions should be performed through protected
-- server-side/Edge Functions. Never put a Supabase service-role key
-- in the browser.
